name: Documentation Build

on:
  push:
    branches: [ main ]
    paths:
      - 'documentation/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'documentation/**'
      - '**.md'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install documentation tools
      run: |
        pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin
    
    - name: Validate Markdown
      run: |
        npm install -g markdownlint-cli
        markdownlint '**/*.md' --ignore node_modules --ignore venv
    
    - name: Check for broken links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: '.github/markdown-link-check-config.json'
    
    - name: Generate documentation site
      run: |
        # Create mkdocs.yml if it doesn't exist
        if [ ! -f mkdocs.yml ]; then
          cat > mkdocs.yml << EOF
        site_name: Bevco Executive Dashboard
        site_description: Power BI Dashboard Documentation
        theme:
          name: material
          palette:
            primary: blue
            accent: light blue
        nav:
          - Home: README.md
          - Quick Start: QUICKSTART.md
          - Project Summary: PROJECT_SUMMARY.md
          - Technical:
            - Deployment Guide: documentation/technical/Deployment_Guide.md
          - User Guides:
            - Executive Dashboard: documentation/user-guides/Executive_Dashboard_User_Guide.md
          - Power BI:
            - Data Model: powerbi/datasets/BevcoDataModel.md
            - Dashboard Structure: powerbi/reports/Dashboard_Structure.md
        EOF
        fi
        
        # Build documentation
        mkdocs build
    
    - name: Upload documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation-site
        path: site/
    
    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site