name: Release Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy openpyxl
    
    - name: Generate fresh sample data
      run: |
        python scripts/etl/generate_master_data.py
    
    - name: Run data quality check
      run: |
        python scripts/etl/data_quality_check.py
    
    - name: Create release package
      run: |
        # Create release directory
        mkdir -p release/bevco-dashboard
        
        # Copy essential files
        cp -r data release/bevco-dashboard/
        cp -r scripts release/bevco-dashboard/
        cp -r powerbi release/bevco-dashboard/
        cp -r documentation release/bevco-dashboard/
        cp README.md release/bevco-dashboard/
        cp QUICKSTART.md release/bevco-dashboard/
        cp PROJECT_SUMMARY.md release/bevco-dashboard/
        
        # Create requirements file
        cat > release/bevco-dashboard/requirements.txt << EOF
        pandas>=1.3.0
        numpy>=1.21.0
        openpyxl>=3.0.0
        EOF
        
        # Create installation script
        cat > release/bevco-dashboard/install.sh << 'EOF'
        #!/bin/bash
        echo "Installing Bevco Executive Dashboard..."
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        echo "Installation complete! Run ./scripts/setup.sh to generate data."
        EOF
        
        chmod +x release/bevco-dashboard/install.sh
        chmod +x release/bevco-dashboard/scripts/setup.sh
        
        # Create zip archive
        cd release
        zip -r bevco-dashboard-${{ github.event.inputs.version || github.ref_name }}.zip bevco-dashboard/
        
        # Create tar.gz archive
        tar -czf bevco-dashboard-${{ github.event.inputs.version || github.ref_name }}.tar.gz bevco-dashboard/
    
    - name: Create Release Notes
      run: |
        cat > release/RELEASE_NOTES.md << EOF
        # Bevco Executive Dashboard Release ${{ github.event.inputs.version || github.ref_name }}
        
        ## What's Included
        
        - Complete Power BI dashboard solution
        - Sample master data for all business areas
        - Automated setup scripts
        - Comprehensive documentation
        - DAX measures library (60+ measures)
        
        ## Quick Start
        
        1. Extract the archive
        2. Run \`install.sh\` (Linux/Mac) or \`install.bat\` (Windows)
        3. Run \`scripts/setup.sh\` to generate sample data
        4. Open Power BI Desktop and follow QUICKSTART.md
        
        ## Key Features
        
        - Executive Summary Dashboard
        - Sales & Revenue Analytics
        - Financial Management
        - Operational Excellence Metrics
        - Customer & Market Intelligence
        - People & Performance Analytics
        
        ## Requirements
        
        - Power BI Desktop (latest version)
        - Python 3.8+
        - 500MB free disk space
        
        ## Support
        
        For issues and questions, please visit the GitHub repository.
        EOF
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version || github.ref_name }}
        name: Bevco Dashboard ${{ github.event.inputs.version || github.ref_name }}
        body_path: release/RELEASE_NOTES.md
        files: |
          release/bevco-dashboard-*.zip
          release/bevco-dashboard-*.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}